version: 2
jobs:
  build:
    working_directory: ~/repo
    machine:
      node:
        version: 8.9.1
    dependencies:
      override:
        - nvm install 8 && npm install
    test:
      override:
        - nvm use 8 && npm run test-server-all
        - nvm use 8 && npm run ci
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm run test
      # - run: $(npm bin)/cypress run --record

      - deploy:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git master